# Generated by Django 4.2.6 on 2023-11-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_die_delete_dice_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
